### PR TITLE
upgrade requests and httplib2 so we can have SNI support for py2

### PR DESCRIPTION
**Pull request by emirozer**

### CODE REVIEW

**Comment by emirozer** [comment]
following libraries come as requests deps:

* chardet
* idna
* certifi
* urllib3

**Comment by emirozer** [comment]
```
Starting app 55309649-05d3-4aa9-9f8d-30316ca7e02c in org testfree / space apps as admin...
Creating container
Successfully created container
Downloading app package...
Downloaded app package (10.7M)
Staging...
INFO: buildpack compile completed
Exit status 0
Staging complete
Uploading droplet, build artifacts cache...
Uploading droplet...
Uploading build artifacts cache...
Uploaded build artifacts cache (2.5M)
Uploaded droplet (13.9M)
Uploading complete
Destroying container
Successfully destroyed container

0 of 1 instances running, 1 starting
1 of 1 instances running

App started


OK

App 55309649-05d3-4aa9-9f8d-30316ca7e02c was started using this command `python start.py`

Showing health and status for app 55309649-05d3-4aa9-9f8d-30316ca7e02c in org testfree / space apps as admin...
OK

requested state: started
instances: 1/1
usage: 2G x 1 instances
urls: wowsuchagoodapp.test.mxapps.io
last uploaded: Thu Jun 15 15:27:51 UTC 2017
stack: cflinuxfs2
buildpack: https://github.com/mendix/cf-mendix-buildpack.git#upgrade_requests_httplib2

     state     since                    cpu    memory         disk           details
#0   running   2017-06-15 05:30:02 PM   0.0%   425.9M of 2G   707.5M of 4G
```

**Comment by emirozer** [comment]
cc @xiwenc @djvdorp 

This is a blocker at the moment, because the buildstatus callback fails with SNI issue

**Comment by emirozer** [comment]
But it very sadly seems not enough... 

```
OUT ERROR: Certificate did not match expected hostname: blah.test.mendix.com. Certificate: {'notAfter': 'Jun 12 23:59:59 2020 GMT', 'subjectAltName': (('DNS', '*.test.mxapps.io'),), 'subject': ((('commonName', u'*.test.mxapps.io'),),)}
```

where blah is one of our services that apps get created..

**Comment by emirozer** [comment]
i think we also have to upgrade the python version... so if you have time this is rather urgent that would be nice to add as well

**Comment by emirozer** [comment]
```2017-06-15T17:38:33.68+0200 [STG/0]      ERR   SNIMissingWarning
2017-06-15T17:38:33.68+0200 [STG/0]      ERR /tmp/buildpacks/3ba1da2c97ce4a74c6a603c1f0f20bfe/lib/urllib3/util/ssl_.py:133: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
```

**Comment by pommi** [comment]
Can you add to the commit message which specific versions we upgraded to?

**Comment by emirozer** [comment]
I added the version numbers to the commit message.

Whats not clear about the errors in the comments ?

**Comment by pommi** [comment]
Thanks

About the comments: First I see a commit in the timeline and after that you say that it doesn't work and we have to upgrade to a newer python version. Do your changes add SNI support while using python 2.7.4 or not? What do you mean with `py2` in your commit message, python 2? Python 2.7.9 and up support SNI already, so that means these changes add SNI support for python <= 2.7.9, right?

Could you also mention something about the versions of `certifi`, `chardet`, `idna` and `urllib3`, which are now included?

**Pull request closed without merging**
