### PR TITLE
Update Java

### PR DESCRIPTION
**Pull request by pommi**

### CODE REVIEW

**Comment by xiwenc** [comment]
Looks good to me. There's just a minor down side with dropping JRE: when MDA is pushed with the buildpack the droplet produced on non-mendix-cloud systems are bigger than JRE.

**Comment by pommi** [comment]
@xiwenc Makes sense. Uncompressed JDK is ~160MB bigger then JRE. The commits I just pushed add back support for JRE.

**Comment by djvdorp** [comment]
LGTM! Nice commit messages Pim!

**Comment by jtwaleson** [comment]
I've rebased this onto master and added some changes. Let's continue in pull/118

**Pull request closed without merging**
