### PR TITLE
Bug 82 configure custom runtime settings and constants

### PR DESCRIPTION
**Pull request by xiwenc**

### CODE REVIEW

**Comment by emirozer** [comment]
LGTM

**Comment by xiwenc** [comment]
don't merge yet, I'm testing the new feature and writing test cases

**Comment by djvdorp** [comment]
The implementation looks good so far (so LGTM for that), if you notify us when testing is done we can merge this whenever you want I think?

**Comment by djvdorp** [comment]
LGTM

**Pull request merged**
