### PR TITLE
improve logging about retrieving the Mendix Runtime version

### PR DESCRIPTION
**Pull request by pommi**

### CODE REVIEW

**Comment by emirozer** [comment]
LGTM

**Comment by emirozer** [comment]
@pommi the guys apparently want people to bump the version number in  start.py

https://github.com/mendix/cf-mendix-buildpack/blob/master/start.py#L26

**Comment by djvdorp** [comment]
Looks good, but version number should be bumped and there is another change you want to do in `start.py` I think where we have similar logline(s) that could be more verbose, as you change did?

**Comment by emirozer** [comment]
https://github.com/mendix/cf-mendix-buildpack/blob/master/start.py#L631

**Pull request merged**
