### PR TITLE
M2EE_PASSWORD 

### PR DESCRIPTION
**Pull request by emirozer**
With this change, the newly deployed apps will simply won't have any user unless they do change admin pass.

### CODE REVIEW

**Comment by pommi** [comment]
Can we remove all of the `ADMIN_PASSWORD` stuff? Do we have to do `m2ee.client.create_admin_user` on startup? Maybe this can be removed as well? When a user needs to access it's App via MxAdmin, the admin password needs to be set anyway from the portal.

**Comment by djvdorp** [comment]
I think `m2ee.client.create_admin_user` on startup might still be needed because of InstaDeploy? Not sure, just thinking out loud here, got notified via email about your comments haha.

**Comment by emirozer** [comment]
I don't thin we can, users that want to run Mendix on other Cloud Foundry providers will have to set ADMIN_PASSWORD in the missing case of the M2EE_PASSWORD

@pommi @djvdorp

**Comment by pommi** [comment]
Good point!

**Comment by pommi** [comment]
The rest looks good.

**Pull request merged**
